In [1]:
!pip install faker

Collecting faker
  Downloading faker-37.8.0-py3-none-any.whl.metadata (15 kB)
Requirement already satisfied: tzdata in c:\users\hp\appdata\local\programs\python\python313\lib\site-packages (from faker) (2025.2)
Downloading faker-37.8.0-py3-none-any.whl (2.0 MB)
   ---------------------------------------- 0.0/2.0 MB ? eta -:--:--
   ----- ---------------------------------- 0.3/2.0 MB ? eta -:--:--
   ---------------------------------------- 2.0/2.0 MB 4.8 MB/s  0:00:00
Installing collected packages: faker
Successfully installed faker-37.8.0

In [4]:
# Re-run the data generation script to ensure files exist
# data_generator.py
import pandas as pd
import random
from faker import Faker
import json
from ast import literal_eval

fake = Faker('en_IN')

# Base pools and dynamic expansion helpers
BASE_SKILLS = [
    # Tech & data
    'Python','Java','C++','C','JavaScript','TypeScript','Go','Rust','SQL','NoSQL','HTML','CSS','React','Angular','Vue','Django','Flask','Spring','Node.js','Express',
    'Data Analysis','Data Engineering','Machine Learning','Deep Learning','NLP','Computer Vision','Statistics','Excel','Power BI','Tableau','R','SPSS','STATA','MATLAB',
    'Cloud','AWS','Azure','GCP','DevOps','CI/CD','Docker','Kubernetes','Linux','Git','GitHub','GitLab','Bash','Powershell',
    'Networking','Cybersecurity','Penetration Testing','SIEM','Vulnerability Assessment','ISO 27001',
    'UI/UX','Figma','Adobe XD','Canva','Graphic Design','Design Systems','Accessibility',
    # Business & generic
    'Product Management','Project Management','Agile','Scrum','Jira','Confluence','Documentation','Technical Writing','Business Analysis','Requirements Gathering',
    'Marketing','Digital Marketing','SEO','SEM','Content Writing','Copywriting','Social Media','Branding','Email Marketing','Google Analytics',
    'Sales','Inside Sales','Field Sales','Lead Generation','CRM','Salesforce','HubSpot','Customer Relationship',
    'Finance','Accounting','Auditing','Taxation','Investment Research','Financial Modeling','Tally','GST','Bookkeeping',
    'Operations','Supply Chain','Logistics','Procurement','Inventory Management','Warehouse Operations','Cold Chain',
    'HR','Recruitment','Talent Acquisition','Payroll','L&D','Compliance','Labor Laws','Employee Engagement',
    'Quality Assurance','Manual Testing','Automation Testing','Selenium','JMeter','Postman','Six Sigma','Lean','5S','ISO 9001',
    # Soft skills & digital literacy
    'Communication','Presentation','Public Speaking','Teamwork','Leadership','Problem Solving','Critical Thinking','Time Management','Adaptability','Creativity',
    'Customer Service','Basic Computer Skills','MS Word','MS Excel','MS PowerPoint','Typing','Data Entry',
    # Vocational & sector-specific
    'AutoCAD','SolidWorks','CATIA','CAD','CAM','CNC','3D Printing','PLC','SCADA','Industrial Safety',
    'Electrical Wiring','Electronics Repair','PCB Design','Arduino','Raspberry Pi','IoT','Embedded Systems','VLSI Basics',
    'Welding','Carpentry','Plumbing','Masonry','Painting','Solar Installation','Wind Turbine Basics',
    'GIS','Remote Sensing','Surveying','Drones','UAV Operation',
    'Food Safety','HACCP','FSSAI Compliance','Food Processing','Packaging',
    'Pharmacy Assistance','Phlebotomy','Nursing Assistance','Medical Coding','EHR Systems','Telemedicine Support','Laboratory Technician',
    'Retail Operations','Cashier','POS Systems','Merchandising','Store Management',
    'Insurance Underwriting','Claims Processing','KYC','AML','Risk Assessment','Microfinance',
    'Rural Outreach','Field Survey','Social Work','NGO Program Support','CSR Implementation','Community Mobilization',
    'PowerApps','Power Automate','SharePoint','ServiceNow','Zoho',
]
BASE_INDUSTRIES = [
    # Core sectors
    'Technology','Finance','Healthcare','Manufacturing','Retail','Education','Media','Consulting','Telecommunications','Energy','Transportation',
    'Agriculture','Automotive','Pharmaceuticals','Biotechnology','Aerospace','Defense','Hospitality','Tourism','Real Estate','Construction',
    # Services & platforms
    'E-commerce','Logistics','Warehousing','Cold Chain','Courier','BPO/ITES','KPO','Shared Services','Public Sector','Non-Profit','Banking','Insurance',
    # Emerging & domain
    'FinTech','EdTech','HealthTech','GovTech','AgriTech','Food Processing','CleanTech','Waste Management','Water & Sanitation','Environmental Services','Climate & Sustainability',
    'Renewable Energy','Solar','Wind','Oil & Gas','Mining','Metals',
    # Rural & traditional
    'Dairy','Poultry','Fisheries','Horticulture','Handloom','Handicrafts','Textiles','Leather',
    # Urban infra & mobility
    'Smart Cities','Urban Development','Roads & Highways','Railways','Metro Rail','Ports & Shipping','Aviation',
    # Social & governance
    'Public Health','Social Welfare','Disaster Management','Rural Development','Panchayati Raj','MSME','Startups & Incubation','CSR',
    # Lifestyle & services
    'Food & Beverage','Sports','Entertainment','Gaming','Legal','Advertising','Marketing Services','Research','Analytics','Cybersecurity','Cloud Services','Beauty & Wellness','Event Management',
]
BASE_TIER1_CITIES = ['Mumbai','Delhi','Bengaluru','Chennai','Kolkata','Hyderabad','Pune','Ahmedabad']
BASE_TIER2_CITIES = [
    'Jaipur','Surat','Lucknow','Kanpur','Nagpur','Indore','Thane','Bhopal','Visakhapatnam','Vadodara','Firozabad','Ludhiana','Agra','Nashik','Faridabad','Meerut',
    'Rajkot','Kalyan','Vasai-Virar','Varanasi','Srinagar','Aurangabad','Dhanbad','Amritsar','Navi Mumbai','Allahabad','Ranchi','Haora','Coimbatore','Jabalpur','Gwalior',
    'Vijayawada','Jodhpur','Madurai','Raipur','Kota','Guwahati','Chandigarh','Solapur','Hubliâ€“Dharwad','Bareilly','Moradabad','Mysore','Gurgaon','Aligarh','Jalandhar',
    'Tiruchirappalli','Bhubaneswar','Salem','Warangal','Mira-Bhayandar','Thiruvananthapuram','Bhiwandi','Saharanpur','Guntur','Amravati','Bikaner','Noida','Jamshedpur'
]
BASE_TIER3_CITIES = [
    'Ujjain','Nellore','Jamnagar','Belgaum','Mangalore','Ambattur','Tirunelveli','Malegaon','Gaya','Jalgaon','Udaipur','Maheshtala','Tirupati','Davanagere','Kozhikode',
    'Akola','Kurnool','Bokaro','Bellary','Patiala','South Dumdum','Aizawl','Sambalpur','Nadiad','Kakinada','Rajahmundry','Shimoga','Mysuru','Siliguri','Durgapur',
    'Panipat','Bhiwani','Rohtak','Sonipat','Yamunanagar','Ambala','Hisar','Karnal','Rewari','Kurukshetra','Palwal','Kaithal','Sirsa','Fatehabad','Jhajjar','Panvel'
]

TARGET_SKILLS_COUNT = 200
TARGET_INDUSTRIES_COUNT = 100
TARGET_CITIES_COUNT = 350

# Build expanded pools deterministically
random.seed(42)

def build_skills_pool():
    pool = list(dict.fromkeys(BASE_SKILLS))
    idx = 0
    while len(pool) < TARGET_SKILLS_COUNT:
        idx += 1
        pool.append(f"Skill_{idx:03d}")
    return pool

def build_industries_pool():
    pool = list(dict.fromkeys(BASE_INDUSTRIES))
    idx = 0
    while len(pool) < TARGET_INDUSTRIES_COUNT:
        idx += 1
        pool.append(f"Industry_{idx:03d}")
    return pool

def build_cities_pool():
    base = list(dict.fromkeys(BASE_TIER1_CITIES + BASE_TIER2_CITIES + BASE_TIER3_CITIES))
    # Fast deterministic fill to target size without Faker overhead
    while len(base) < TARGET_CITIES_COUNT:
        base.append(f"City_{len(base)+1:03d}")
    return base

SKILLS_POOL = build_skills_pool()
INDUSTRIES_POOL = build_industries_pool()
CITIES_POOL = build_cities_pool()

# Aspirations and roles
BASE_ASPIRATIONS = [
    'Software Developer','Data Analyst','Data Scientist','ML Engineer','DevOps Engineer','Cloud Engineer','UI/UX Designer','Product Manager','Project Manager',
    'Business Analyst','Marketing Associate','Digital Marketer','Content Writer','Copywriter','Finance Intern','Financial Analyst','HR Assistant','Recruiter',
    'Operations Associate','Supply Chain Analyst','QA Engineer','Automation Tester','Cybersecurity Analyst','Network Engineer','Technical Support','Customer Support'
]

def build_aspirations_pool():
    pool = list(dict.fromkeys(BASE_ASPIRATIONS))
    idx = 0
    while len(pool) < 120:
        idx += 1
        pool.append(f"Aspiration_{idx:03d}")
    return pool

ASPIRATIONS_POOL = build_aspirations_pool()
ROLES_POOL = list(dict.fromkeys(BASE_ASPIRATIONS + ['Content Strategist','Full Stack Developer','Mobile App Developer','Data Engineer','Growth Marketer']))
COMPANIES = ['TCS','Infosys','Wipro','HCL','HDFC Bank','ICICI Bank','Reliance','Mahindra','L&T','Bajaj','Aditya Birla','Tata Steel','Maruti Suzuki','Tech Mahindra','Cognizant']


def generate_students(n=1500):
    students = []
    for i in range(n):
        student = {
            'id': f'STU{i:03d}',
            'name': fake.name(),
            'age': random.randint(18, 25),
            'education': random.choice(['B.Tech','B.Sc','BBA','B.Com','MBA','BA','BCA','MCA']),
            'skills': random.sample(SKILLS_POOL, k=random.randint(3, 8)),
            'aspirations': random.sample(ASPIRATIONS_POOL, k=random.randint(1, 3)),
            'location': random.choice(CITIES_POOL),
            'industry_interest': random.choice(INDUSTRIES_POOL),
            'experience_months': random.randint(0, 24)
        }
        students.append(student)
    return pd.DataFrame(students)


def generate_internships(n=1500):
    internships = []
    for i in range(n):
        internship = {
            'id': f'INT{i:03d}',
            'company': random.choice(COMPANIES),
            'role': random.choice(ROLES_POOL),
            'location': random.choice(CITIES_POOL),
            'industry': random.choice(INDUSTRIES_POOL),
            'required_skills': random.sample(SKILLS_POOL, k=random.randint(2, 6)),
            'duration_months': random.choice([3, 6, 12]),
            'stipend': random.randint(5000, 25000)
        }
        internships.append(internship)
    return pd.DataFrame(internships)

students_df = generate_students(1500)
internships_df = generate_internships(1500)

students_df.to_csv('./students.csv', index=False)
internships_df.to_csv('./internships.csv', index=False)

print("âœ… Data generated successfully!")
print(f"Students: {len(students_df)}, Internships: {len(internships_df)}")

# Load the generated dataframes
students_df = pd.read_csv('students.csv')
internships_df = pd.read_csv('internships.csv')

# Inspect data
print("Students DataFrame Info:")
students_df.info()
print("\nStudents DataFrame Head:")
display(students_df.head())
print("\nStudents Missing Values:")
print(students_df.isnull().sum())

print("\nInternships DataFrame Info:")
internships_df.info()
print("\nInternships DataFrame Head:")
display(internships_df.head())
print("\nInternships Missing Values:")
print(internships_df.isnull().sum())

# Convert list-like string columns to clean, comma-joined strings using safe parsing
for col in ['skills','aspirations']:
    if students_df[col].dtype == object:
        students_df[col] = students_df[col].apply(lambda x: ', '.join(literal_eval(x)) if isinstance(x, str) and x.startswith('[') else (x if isinstance(x, str) else ''))

if internships_df['required_skills'].dtype == object:
    internships_df['required_skills'] = internships_df['required_skills'].apply(lambda x: ', '.join(literal_eval(x)) if isinstance(x, str) and x.startswith('[') else (x if isinstance(x, str) else ''))

print("\nStudents DataFrame with processed skills & aspirations:")
display(students_df.head())
print("\nInternships DataFrame with processed required_skills:")
display(internships_df.head())

âœ… Data generated successfully!
Students: 1500, Internships: 1500
Students DataFrame Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1500 entries, 0 to 1499
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id                 1500 non-null   object
 1   name               1500 non-null   object
 2   age                1500 non-null   int64
 3   education          1500 non-null   object
 4   skills             1500 non-null   object
 5   aspirations        1500 non-null   object
 6   location           1500 non-null   object
 7   industry_interest  1500 non-null   object
 8   experience_months  1500 non-null   int64
dtypes: int64(2), object(7)
memory usage: 105.6+ KB

Students DataFrame Head:

,id,name,age,education,skills,aspirations,location,industry_interest,experience_months
0,STU000,Isaiah Natarajan,19,B.Tech,"['Requirements Gathering', 'Project Management...","['Digital Marketer', 'Aspiration_050', 'Aspira...",Visakhapatnam,Manufacturing,2
1,STU001,Patrick Chatterjee,21,B.Com,"['Raspberry Pi', 'Go', 'CAD', 'Penetration Tes...","['Aspiration_028', 'Aspiration_003', 'Aspirati...",City_302,HealthTech,0
2,STU002,Chavvi Sarin,20,BCA,"['Marketing', 'CI/CD', 'Figma', 'Social Work',...",['Digital Marketer'],City_195,Automotive,11
3,STU003,Hemal Raval,23,MBA,"['Store Management', 'JMeter', 'MS PowerPoint']",['Aspiration_093'],City_194,Transportation,17
4,STU004,Jagrati Sule,22,BA,"['Cybersecurity', 'Telemedicine Support', 'Spr...","['Marketing Associate', 'Aspiration_084']",City_120,Automotive,12

Students Missing Values:
id                   0
name                 0
age                  0
education            0
skills               0
aspirations          0
location             0
industry_interest    0
experience_months    0
dtype: int64

Internships DataFrame Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1500 entries, 0 to 1499
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id               1500 non-null   object
 1   company          1500 non-null   object
 2   role             1500 non-null   object
 3   location         1500 non-null   object
 4   industry         1500 non-null   object
 5   required_skills  1500 non-null   object
 6   duration_months  1500 non-null   int64
 7   stipend          1500 non-null   int64
dtypes: int64(2), object(6)
memory usage: 93.9+ KB

Internships DataFrame Head:

,id,company,role,location,industry,required_skills,duration_months,stipend
0,INT000,Aditya Birla,Marketing Associate,City_116,Education,"['SQL', 'Merchandising', 'Express', 'Data Engi...",12,21544
1,INT001,Mahindra,Technical Support,City_168,Metals,"['Postman', 'Problem Solving']",6,23105
2,INT002,Tata Steel,Full Stack Developer,City_269,Finance,"['Powershell', 'ISO 27001']",3,5963
3,INT003,Bajaj,ML Engineer,City_172,Industry_014,"['Power BI', 'AutoCAD', 'STATA', 'PCB Design',...",3,13008
4,INT004,Tata Steel,Content Writer,City_171,Roads & Highways,"['Documentation', 'Store Management', 'Digital...",12,18615

Internships Missing Values:
id                 0
company            0
role               0
location           0
industry           0
required_skills    0
duration_months    0
stipend            0
dtype: int64

Students DataFrame with processed skills & aspirations:

,id,name,age,education,skills,aspirations,location,industry_interest,experience_months
0,STU000,Isaiah Natarajan,19,B.Tech,"Requirements Gathering, Project Management, Ca...","Digital Marketer, Aspiration_050, Aspiration_029",Visakhapatnam,Manufacturing,2
1,STU001,Patrick Chatterjee,21,B.Com,"Raspberry Pi, Go, CAD, Penetration Testing, Ca...","Aspiration_028, Aspiration_003, Aspiration_032",City_302,HealthTech,0
2,STU002,Chavvi Sarin,20,BCA,"Marketing, CI/CD, Figma, Social Work, Salesforce",Digital Marketer,City_195,Automotive,11
3,STU003,Hemal Raval,23,MBA,"Store Management, JMeter, MS PowerPoint",Aspiration_093,City_194,Transportation,17
4,STU004,Jagrati Sule,22,BA,"Cybersecurity, Telemedicine Support, Spring, C...","Marketing Associate, Aspiration_084",City_120,Automotive,12

Internships DataFrame with processed required_skills:

,id,company,role,location,industry,required_skills,duration_months,stipend
0,INT000,Aditya Birla,Marketing Associate,City_116,Education,"SQL, Merchandising, Express, Data Engineering,...",12,21544
1,INT001,Mahindra,Technical Support,City_168,Metals,"Postman, Problem Solving",6,23105
2,INT002,Tata Steel,Full Stack Developer,City_269,Finance,"Powershell, ISO 27001",3,5963
3,INT003,Bajaj,ML Engineer,City_172,Industry_014,"Power BI, AutoCAD, STATA, PCB Design, Basic Co...",3,13008
4,INT004,Tata Steel,Content Writer,City_171,Roads & Highways,"Documentation, Store Management, Digital Marke...",12,18615

In [5]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

# Build field-specific text features
students_df['skills_asp_text'] = students_df.apply(
    lambda row: f"{row['skills']} {row['aspirations']}", axis=1
)
internships_df['reqskills_role_text'] = internships_df.apply(
    lambda row: f"{row['required_skills']} {row['role']}", axis=1
)

students_df['industry_text'] = students_df['industry_interest'].apply(lambda v: f"industry:{v}")
internships_df['industry_text'] = internships_df['industry'].apply(lambda v: f"industry:{v}")

students_df['location_text'] = students_df['location'].apply(lambda v: f"location:{v}")
internships_df['location_text'] = internships_df['location'].apply(lambda v: f"location:{v}")

# Vectorizers per field
vec_main = TfidfVectorizer(ngram_range=(1, 2), min_df=2)
vec_industry = TfidfVectorizer()
vec_location = TfidfVectorizer()

# Fit on combined corpora for each field
main_corpus = students_df['skills_asp_text'].tolist() + internships_df['reqskills_role_text'].tolist()
industry_corpus = students_df['industry_text'].tolist() + internships_df['industry_text'].tolist()
location_corpus = students_df['location_text'].tolist() + internships_df['location_text'].tolist()

main_matrix = vec_main.fit_transform(main_corpus)
industry_matrix = vec_industry.fit_transform(industry_corpus)
location_matrix = vec_location.fit_transform(location_corpus)

# Split student/internship parts
student_main = main_matrix[:len(students_df)]
intern_main = main_matrix[len(students_df):]

student_industry = industry_matrix[:len(students_df)]
intern_industry = industry_matrix[len(students_df):]

student_location = location_matrix[:len(students_df)]
intern_location = location_matrix[len(students_df):]

# Field-wise cosine similarities
sim_main = cosine_similarity(student_main, intern_main)
sim_industry = cosine_similarity(student_industry, intern_industry)
sim_location = cosine_similarity(student_location, intern_location)

# Weighted combination (tuneable)
W_MAIN, W_INDUSTRY, W_LOCATION = 0.6, 0.2, 0.2
similarity_matrix = (W_MAIN * sim_main) + (W_INDUSTRY * sim_industry) + (W_LOCATION * sim_location)

print("Shapes -> main:", student_main.shape, intern_main.shape)
print("Shapes -> industry:", student_industry.shape, intern_industry.shape)
print("Shapes -> location:", student_location.shape, intern_location.shape)
print("Final similarity matrix:", similarity_matrix.shape)

Shapes -> main: (1500, 2780) (1500, 2780)
Shapes -> industry: (1500, 121) (1500, 121)
Shapes -> location: (1500, 355) (1500, 355)
Final similarity matrix: (1500, 1500)

In [7]:
# Similarity already computed using weighted multi-field approach above
print("Shape of similarity matrix:", similarity_matrix.shape)

Shape of similarity matrix: (1500, 1500)

In [8]:
import numpy as np

# Number of recommendations to generate for each student
N = 5

# Dictionary to store recommendations for each student
student_recommendations = {}

# Iterate through each student's similarity scores
for i in range(len(students_df)):
    student_id = students_df.loc[i, 'id']
    # Get the similarity scores for the current student
    student_similarity_scores = similarity_matrix[i, :]

    # Get the indices of the top N internships with the highest similarity scores
    top_internship_indices = np.argsort(student_similarity_scores)[::-1][:N]

    # Get the details of the recommended internships
    recommended_internships = internships_df.iloc[top_internship_indices].copy()
    recommended_internships['similarity'] = student_similarity_scores[top_internship_indices]
    recommended_internships = recommended_internships.to_dict('records')

    # Store the recommendations
    student_recommendations[student_id] = recommended_internships

# Print recommendations for a few sample students
sample_student_ids = list(student_recommendations.keys())[:5]

print("Sample Internship Recommendations:")
for student_id in sample_student_ids:
    stu = students_df[students_df['id'] == student_id].iloc[0]
    print(f"\nRecommendations for Student ID: {student_id} | Location: {stu['location']} | Aspirations: {stu['aspirations']}")
    for rec in student_recommendations[student_id]:
        print(f"  - {rec['role']} at {rec['company']} in {rec['location']} (Industry: {rec['industry']})")
        print(f"    Skills: {rec['required_skills']} | Score: {rec['similarity']:.3f}")

Sample Internship Recommendations:

Recommendations for Student ID: STU000 | Location: Visakhapatnam | Aspirations: Digital Marketer, Aspiration_050, Aspiration_029
  - Digital Marketer at Aditya Birla in City_330 (Industry: Manufacturing)
    Skills: Food Safety, Microfinance, Flask | Score: 0.322
  - Project Manager at Aditya Birla in Visakhapatnam (Industry: Startups & Incubation)
    Skills: Raspberry Pi, GitLab, EHR Systems, Excel, JMeter, Communication | Score: 0.223
  - Cybersecurity Analyst at TCS in City_138 (Industry: Manufacturing)
    Skills: Rural Outreach, Supply Chain, Bookkeeping, Store Management | Score: 0.216
  - Operations Associate at Tech Mahindra in Jodhpur (Industry: Telecommunications)
    Skills: Claims Processing, Project Management | Score: 0.213
  - Copywriter at Reliance in Visakhapatnam (Industry: Research)
    Skills: NoSQL, Confluence | Score: 0.206

Recommendations for Student ID: STU001 | Location: City_302 | Aspirations: Aspiration_028, Aspiration_003, Aspiration_032
  - Digital Marketer at L&T in City_215 (Industry: HealthTech)
    Skills: Cashier, Angular, Tableau, Networking, GCP, Confluence | Score: 0.258
  - Financial Analyst at Infosys in City_302 (Industry: Social Welfare)
    Skills: Communication, Retail Operations, Teamwork, CAD, STATA | Score: 0.245
  - Customer Support at Tech Mahindra in City_302 (Industry: Research)
    Skills: C++, Figma, Procurement, 3D Printing | Score: 0.206
  - Marketing Associate at Aditya Birla in City_302 (Industry: Handloom)
    Skills: Zoho, Sales, SharePoint, Retail Operations | Score: 0.206
  - Technical Support at ICICI Bank in City_302 (Industry: Aerospace)
    Skills: Bash, Operations, SPSS, SEO | Score: 0.206

Recommendations for Student ID: STU002 | Location: City_195 | Aspirations: Digital Marketer
  - Network Engineer at HDFC Bank in Bareilly (Industry: Automotive)
    Skills: SharePoint, CI/CD, Go, Warehouse Operations | Score: 0.314
  - Automation Tester at Bajaj in City_195 (Industry: FinTech)
    Skills: SIEM, CAD, Salesforce | Score: 0.279
  - Marketing Associate at Infosys in Kaithal (Industry: Automotive)
    Skills: NGO Program Support, Figma, Jira | Score: 0.278
  - Marketing Associate at HDFC Bank in City_120 (Industry: Automotive)
    Skills: Supply Chain, Figma, Community Mobilization, Angular | Score: 0.276
  - Digital Marketer at Cognizant in City_216 (Industry: Legal)
    Skills: Azure, VLSI Basics, Procurement, Customer Relationship, Salesforce | Score: 0.269

Recommendations for Student ID: STU003 | Location: City_194 | Aspirations: Aspiration_093
  - Data Scientist at Infosys in City_243 (Industry: Transportation)
    Skills: Packaging, Store Management, Django, Graphic Design, PCB Design | Score: 0.300
  - Data Engineer at HCL in City_234 (Industry: Industry_009)
    Skills: FSSAI Compliance, MS Excel, CSR Implementation, PLC, Store Management, JMeter | Score: 0.233
  - Network Engineer at Wipro in City_120 (Industry: Transportation)
    Skills: Remote Sensing, Plumbing, Six Sigma, Power Automate, MS Excel | Score: 0.226
  - Marketing Associate at Reliance in City_194 (Industry: Rural Development)
    Skills: Supply Chain, Electronics Repair, Time Management, Communication, TypeScript, Figma | Score: 0.223
  - Product Manager at Aditya Birla in City_329 (Industry: Transportation)
    Skills: Time Management, Rural Outreach, React, SharePoint, Communication, Requirements Gathering | Score: 0.223

Recommendations for Student ID: STU004 | Location: City_120 | Aspirations: Marketing Associate, Aspiration_084
  - Marketing Associate at HDFC Bank in City_120 (Industry: Automotive)
    Skills: Supply Chain, Figma, Community Mobilization, Angular | Score: 0.476
  - Marketing Associate at Infosys in Kaithal (Industry: Automotive)
    Skills: NGO Program Support, Figma, Jira | Score: 0.301
  - Cloud Engineer at Aditya Birla in City_139 (Industry: Automotive)
    Skills: Basic Computer Skills, ServiceNow, POS Systems, Graphic Design, Django, HR | Score: 0.281
  - Marketing Associate at Reliance in Kurukshetra (Industry: Rural Development)
    Skills: UAV Operation, GitLab | Score: 0.268
  - Marketing Associate at Mahindra in City_175 (Industry: Automotive)
    Skills: AutoCAD, Employee Engagement, TypeScript, Machine Learning, Teamwork, Welding | Score: 0.264

In [9]:
import random

# Select a few diverse student IDs
sample_student_ids = random.sample(list(student_recommendations.keys()), 5)

print("Qualitative Evaluation of Recommendations:")
print("="*40)

for student_id in sample_student_ids:
    # Get student profile
    student_profile = students_df[students_df['id'] == student_id].iloc[0]

    print(f"\nStudent Profile (ID: {student_id}):")
    print(f"  Skills: {student_profile['skills']}")
    print(f"  Aspirations: {student_profile['aspirations']}")
    print(f"  Education: {student_profile['education']}")
    print(f"  Location: {student_profile['location']}")
    print(f"  Industry Interest: {student_profile['industry_interest']}")

    print("\nRecommended Internships:")
    recommendations = student_recommendations[student_id]
    if recommendations:
        for i, rec in enumerate(recommendations):
            print(f"  {i+1}. {rec['role']} at {rec['company']}")
            print(f"     Location: {rec['location']}, Industry: {rec['industry']}")
            print(f"     Required Skills: {rec['required_skills']} | Score: {rec['similarity']:.3f}")
    else:
        print("  No recommendations found.")

print("\n" + "="*40)
print("Manual Inspection Observations:")
print("The multi-field weighted similarity (skills+aspirations, industry, location) aims to balance skill fit with student aspirations and alignment on industry/location.")
print("Tune weights W_MAIN, W_INDUSTRY, W_LOCATION if certain aspects need more/less influence.")

Qualitative Evaluation of Recommendations:
========================================

Student Profile (ID: STU1059):
  Skills: Design Systems, SEM, HACCP, Presentation, Public Speaking
  Aspirations: Aspiration_025, Aspiration_051, Aspiration_020
  Education: BBA
  Location: City_279
  Industry Interest: Railways

Recommended Internships:
  1. Product Manager at HDFC Bank
     Location: City_222, Industry: Railways
     Required Skills: HR, Git, Masonry, Statistics, C, Presentation | Score: 0.263
  2. Business Analyst at TCS
     Location: City_162, Industry: Railways
     Required Skills: EHR Systems, Cloud, ISO 9001, Statistics, Requirements Gathering, Automation Testing | Score: 0.223
  3. Supply Chain Analyst at L&T
     Location: City_279, Industry: Handloom
     Required Skills: GST, Spring | Score: 0.206
  4. Copywriter at Tech Mahindra
     Location: City_279, Industry: Horticulture
     Required Skills: Leadership, Inventory Management, Copywriting, C++, Statistics, Social Work | Score: 0.206
  5. Digital Marketer at Maruti Suzuki
     Location: City_279, Industry: Industry_001
     Required Skills: Labor Laws, UAV Operation, Technical Writing | Score: 0.206

Student Profile (ID: STU1319):
  Skills: MS PowerPoint, Java, Plumbing, AML
  Aspirations: Aspiration_011, Aspiration_009, Aspiration_046
  Education: B.Com
  Location: City_192
  Industry Interest: Public Health

Recommended Internships:
  1. Mobile App Developer at Reliance
     Location: City_262, Industry: Public Health
     Required Skills: L&D, MS PowerPoint, Store Management, Copywriting | Score: 0.295
  2. Content Strategist at TCS
     Location: City_221, Industry: Public Health
     Required Skills: Bash, Labor Laws, 3D Printing, Excel, Presentation, Plumbing | Score: 0.240
  3. Data Engineer at Reliance
     Location: Ludhiana, Industry: Public Health
     Required Skills: Critical Thinking, MS Excel, GitHub, CATIA, Spring | Score: 0.225
  4. Data Engineer at Cognizant
     Location: City_192, Industry: Technology
     Required Skills: Flask, Django, SharePoint, Finance, CAD | Score: 0.205
  5. Data Analyst at HCL
     Location: City_192, Industry: Logistics
     Required Skills: Payroll, SCADA | Score: 0.205

Student Profile (ID: STU688):
  Skills: PLC, Google Analytics, SolidWorks, Flask, Technical Writing, GIS
  Aspirations: Aspiration_088, Aspiration_035
  Education: B.Tech
  Location: Thiruvananthapuram
  Industry Interest: Ports & Shipping

Recommended Internships:
  1. Cybersecurity Analyst at Bajaj
     Location: Siliguri, Industry: Ports & Shipping
     Required Skills: SEO, JavaScript, Google Analytics, Marketing, Communication | Score: 0.324
  2. Supply Chain Analyst at Maruti Suzuki
     Location: City_317, Industry: Ports & Shipping
     Required Skills: Jira, CRM, Canva, Technical Writing, Embedded Systems | Score: 0.293
  3. Full Stack Developer at Tech Mahindra
     Location: City_188, Industry: Ports & Shipping
     Required Skills: Laboratory Technician, PLC | Score: 0.255
  4. Content Writer at Tata Steel
     Location: City_278, Industry: Ports & Shipping
     Required Skills: Taxation, GIS, Social Media | Score: 0.254
  5. Supply Chain Analyst at Mahindra
     Location: City_273, Industry: Ports & Shipping
     Required Skills: Typing, DevOps, Carpentry, PLC, Labor Laws | Score: 0.246

Student Profile (ID: STU1357):
  Skills: Supply Chain, SolidWorks, Painting, Plumbing
  Aspirations: Aspiration_084, Aspiration_077, Business Analyst
  Education: B.Sc
  Location: Malegaon
  Industry Interest: Event Management

Recommended Internships:
  1. Supply Chain Analyst at Tata Steel
     Location: City_319, Industry: Telecommunications
     Required Skills: SolidWorks, Adobe XD, SPSS | Score: 0.233
  2. Supply Chain Analyst at Reliance
     Location: City_340, Industry: Handicrafts
     Required Skills: Supply Chain, Spring, Cold Chain | Score: 0.232
  3. Cybersecurity Analyst at L&T
     Location: Malegaon, Industry: Non-Profit
     Required Skills: Typing, Critical Thinking, NLP, CSS, Express | Score: 0.227
  4. Cybersecurity Analyst at Mahindra
     Location: City_278, Industry: Event Management
     Required Skills: Compliance, Requirements Gathering, Vue, Customer Service | Score: 0.226
  5. Business Analyst at Tata Steel
     Location: City_291, Industry: Smart Cities
     Required Skills: Welding, Cold Chain | Score: 0.223

Student Profile (ID: STU1168):
  Skills: 5S, Surveying, PCB Design, SharePoint, Recruitment, PowerApps, Merchandising
  Aspirations: Aspiration_004, Aspiration_094
  Education: BA
  Location: City_135
  Industry Interest: Roads & Highways

Recommended Internships:
  1. Content Writer at Tata Steel
     Location: City_171, Industry: Roads & Highways
     Required Skills: Documentation, Store Management, Digital Marketing, PCB Design, R | Score: 0.312
  2. Project Manager at Cognizant
     Location: Guwahati, Industry: GovTech
     Required Skills: 3D Printing, GitHub, PCB Design, C++, SharePoint, C | Score: 0.295
  3. Data Analyst at Bajaj
     Location: City_261, Industry: Roads & Highways
     Required Skills: Surveying, Supply Chain | Score: 0.254
  4. Network Engineer at L&T
     Location: Delhi, Industry: Roads & Highways
     Required Skills: PowerApps, Six Sigma, Arduino | Score: 0.253
  5. Cybersecurity Analyst at Cognizant
     Location: City_135, Industry: Rural Development
     Required Skills: PowerApps, Warehouse Operations, ISO 9001, SIEM | Score: 0.244

========================================
Manual Inspection Observations:
The multi-field weighted similarity (skills+aspirations, industry, location) aims to balance skill fit with student aspirations and alignment on industry/location.
Tune weights W_MAIN, W_INDUSTRY, W_LOCATION if certain aspects need more/less influence.

In [ ]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np

# Re-build student profile text with education level included (already done in previous step)
# students_df['student_profile_text'] = students_df.apply(
#     lambda row: f"{row['skills']} {row['education']} {row['location']} {row['industry_interest']}", axis=1
# )

# Re-build internship text data (already done in previous step)
# internships_df['internship_profile_text'] = internships_df.apply(
#     lambda row: f"{row['required_skills']} {row['location']} {row['industry']}", axis=1
# )

# Combine all text data for fitting the vectorizer
all_text_data = students_df['student_profile_text'].tolist() + internships_df['internship_profile_text'].tolist()

# TF-IDF Vectorization with n-grams (unigrams and bigrams)
vectorizer_ngram = TfidfVectorizer(ngram_range=(1, 2))
tfidf_matrix_ngram = vectorizer_ngram.fit_transform(all_text_data)

# Separate the TF-IDF matrices for students and internships
student_tfidf_matrix_ngram = tfidf_matrix_ngram[:len(students_df)]
internship_tfidf_matrix_ngram = tfidf_matrix_ngram[len(students_df):]

print("Shape of student TF-IDF matrix with n-grams:", student_tfidf_matrix_ngram.shape)
print("Shape of internship TF-IDF matrix with n-grams:", internship_tfidf_matrix_ngram.shape)

# One-hot encode education level for students
# Identify unique education levels
education_levels = students_df['education'].unique().reshape(-1, 1)

# Initialize OneHotEncoder
encoder = OneHotEncoder(handle_unknown='ignore', sparse_output=False)

# Fit and transform the education levels
education_onehot = encoder.fit_transform(students_df[['education']])

# Convert to DataFrame for easier handling
education_onehot_df = pd.DataFrame(education_onehot, columns=[f'education_{level}' for level in encoder.categories_[0]])

# Combine TF-IDF features with one-hot encoded education features for students
# Ensure index alignment
student_features_combined = np.hstack((student_tfidf_matrix_ngram.toarray(), education_onehot_df.values))

print("Shape of combined student features:", student_features_combined.shape)

# For internships, we only have the TF-IDF features from the text data
internship_features_combined = internship_tfidf_matrix_ngram.toarray()

print("Shape of combined internship features:", internship_features_combined.shape)

# Recalculate cosine similarity with combined features
# Note: Cosine similarity works best when features are in the same space.
# Combining TF-IDF (sparse, potentially high-dimensional) with one-hot (dense, low-dimensional)
# directly might not be optimal. A more advanced approach could involve different models
# or feature scaling/weighting. For this refinement step, we'll proceed with direct combination
# for demonstration, acknowledging this limitation.

# To calculate similarity, both matrices need to have the same number of features.
# The internship features do not have the one-hot encoded education levels.
# We need to decide how to handle this discrepancy for similarity calculation.
# Option 1: Only use the TF-IDF features (already done in previous steps, refining with n-grams here).
# Option 2: Find a way to represent education in internships (not directly available).
# Option 3: Use a different model that can handle mixed feature types.

# Given the subtask instructions to refine features and then re-run recommendations,
# and the lack of education data for internships, we will stick to using
# the enhanced text features (with n-grams) for both students and internships
# for the cosine similarity calculation, as this is a direct improvement on the
# existing TF-IDF approach. The one-hot encoding of education is a valid feature
# engineering step for students, but its direct use in cosine similarity with
# internships is limited without a corresponding feature for internships.

# Recalculate cosine similarity using the TF-IDF matrix with n-grams
similarity_matrix_refined = cosine_similarity(student_tfidf_matrix_ngram, internship_tfidf_matrix_ngram)

print("Shape of refined similarity matrix (with n-grams):", similarity_matrix_refined.shape)

# Update the similarity matrix variable for the next steps
similarity_matrix = similarity_matrix_refined

In [11]:

import numpy as np
import random

# Use the existing weighted similarity matrix
N = 5
student_recommendations_refined = {}

for i in range(len(students_df)):
    student_id = students_df.loc[i, 'id']
    scores = similarity_matrix[i, :]
    top_idx = np.argsort(scores)[::-1][:N]
    recs = internships_df.iloc[top_idx].copy()
    recs['similarity'] = scores[top_idx]
    student_recommendations_refined[student_id] = recs.to_dict('records')

# Qualitative check with the same style output
sample_student_ids = random.sample(list(student_recommendations_refined.keys()), 5)

print("Qualitative Evaluation of Refined Recommendations (weighted multi-field):")
print("="*60)

for student_id in sample_student_ids:
    student_profile = students_df[students_df['id'] == student_id].iloc[0]

    print(f"\nStudent Profile (ID: {student_id}):")
    print(f"  Skills: {student_profile['skills']}")
    print(f"  Education: {student_profile['education']}")
    print(f"  Location: {student_profile['location']}")
    print(f"  Industry Interest: {student_profile['industry_interest']}")

    print("\nRecommended Internships (Refined):")
    recommendations_refined = student_recommendations_refined[student_id]
    if recommendations_refined:
        for i, rec in enumerate(recommendations_refined):
            print(f"  {i+1}. {rec['role']} at {rec['company']}")
            print(f"     Location: {rec['location']}, Industry: {rec['industry']}")
            print(f"     Required Skills: {rec['required_skills']}")
    else:
        print("  No refined recommendations found.")

print("\n" + "="*60)
print("Manual Inspection Observations (Refined Recommendations):")
print("Comparing these recommendations to the previous ones, the inclusion of n-grams in TF-IDF may have captured more nuanced relationships between terms.")
print("Look for recommendations that might be more specific or better aligned with combinations of skills or industries mentioned in the student profile.")
print("Note if the rankings of internships have changed significantly or if different internships appear in the top N.")

Qualitative Evaluation of Refined Recommendations (weighted multi-field):
============================================================

Student Profile (ID: STU974):
  Skills: CRM, Selenium, Azure, C
  Education: BBA
  Location: Lucknow
  Industry Interest: Logistics

Recommended Internships (Refined):
  1. Automation Tester at Bajaj
     Location: City_120, Industry: Logistics
     Required Skills: Nursing Assistance, CRM
  2. Product Manager at L&T
     Location: Lucknow, Industry: Industry_001
     Required Skills: Selenium, HubSpot, Sales, AutoCAD, AWS
  3. UI/UX Designer at L&T
     Location: Lucknow, Industry: Agriculture
     Required Skills: Tableau, Manual Testing, Medical Coding, Industrial Safety, CSR Implementation, Inventory Management
  4. Finance Intern at Mahindra
     Location: City_220, Industry: Logistics
     Required Skills: Cloud, Supply Chain, Project Management, Logistics, Quality Assurance
  5. Product Manager at Cognizant
     Location: City_143, Industry: Logistics
     Required Skills: Cloud, Zoho

Student Profile (ID: STU557):
  Skills: Labor Laws, Warehouse Operations, Store Management, PowerApps, SharePoint, Spring
  Education: MCA
  Location: City_247
  Industry Interest: Aerospace

Recommended Internships (Refined):
  1. Mobile App Developer at Mahindra
     Location: City_247, Industry: Environmental Services
     Required Skills: CSS, Spring, Packaging, Lead Generation, Typing, Technical Writing
  2. Cybersecurity Analyst at Cognizant
     Location: City_149, Industry: Aerospace
     Required Skills: Excel, PowerApps, Supply Chain, Lead Generation, Communication
  3. DevOps Engineer at Bajaj
     Location: Srinagar, Industry: Aerospace
     Required Skills: Project Management, Leadership, Inventory Management
  4. Mobile App Developer at Tata Steel
     Location: City_297, Industry: Aerospace
     Required Skills: Marketing, Finance
  5. Automation Tester at HDFC Bank
     Location: City_145, Industry: KPO
     Required Skills: Confluence, Warehouse Operations, Time Management, PowerApps, Arduino, GST

Student Profile (ID: STU901):
  Skills: Telemedicine Support, Azure, GST, Insurance Underwriting, Go, Medical Coding, Payroll, Tally
  Education: B.Sc
  Location: Tiruchirappalli
  Industry Interest: Beauty & Wellness

Recommended Internships (Refined):
  1. Copywriter at L&T
     Location: City_316, Industry: Beauty & Wellness
     Required Skills: Welding, Agile, Medical Coding, SCADA, Procurement, AutoCAD
  2. Business Analyst at Tata Steel
     Location: City_262, Industry: Beauty & Wellness
     Required Skills: Retail Operations, Tally
  3. Mobile App Developer at Wipro
     Location: City_221, Industry: Beauty & Wellness
     Required Skills: Go, UI/UX, Six Sigma
  4. Technical Support at ICICI Bank
     Location: Bhopal, Industry: Beauty & Wellness
     Required Skills: JMeter, GCP
  5. Copywriter at ICICI Bank
     Location: Vijayawada, Industry: Agriculture
     Required Skills: NoSQL, Medical Coding, AML, Insurance Underwriting

Student Profile (ID: STU911):
  Skills: Cold Chain, KYC, Problem Solving, Computer Vision, Community Mobilization
  Education: B.Sc
  Location: City_301
  Industry Interest: Mining

Recommended Internships (Refined):
  1. UI/UX Designer at Wipro
     Location: City_238, Industry: Mining
     Required Skills: C++, Problem Solving
  2. Cybersecurity Analyst at ICICI Bank
     Location: City_209, Industry: Mining
     Required Skills: Accessibility, Cold Chain
  3. Product Manager at HCL
     Location: City_144, Industry: Mining
     Required Skills: Computer Vision, Data Entry
  4. ML Engineer at Tech Mahindra
     Location: City_301, Industry: Industry_011
     Required Skills: Auditing, UAV Operation, Rural Outreach
  5. ML Engineer at ICICI Bank
     Location: City_301, Industry: Marketing Services
     Required Skills: Scrum, Nursing Assistance, Accounting, GitLab, Arduino, Sales

Student Profile (ID: STU889):
  Skills: Arduino, C, ServiceNow, C++, Excel, Typing, Claims Processing, Salesforce
  Education: BBA
  Location: City_246
  Industry Interest: Industry_012

Recommended Internships (Refined):
  1. Network Engineer at Mahindra
     Location: City_124, Industry: Industry_012
     Required Skills: Electrical Wiring, Claims Processing
  2. QA Engineer at Aditya Birla
     Location: Kolkata, Industry: Industry_012
     Required Skills: Claims Processing, Copywriting, Cloud, SCADA, IoT
  3. Content Strategist at HCL
     Location: Sambalpur, Industry: Industry_012
     Required Skills: Labor Laws, Bash, ISO 27001, Claims Processing
  4. Marketing Associate at Reliance
     Location: Nellore, Industry: Industry_012
     Required Skills: HTML, Accounting, Adobe XD, Medical Coding
  5. Content Strategist at Tech Mahindra
     Location: City_246, Industry: Environmental Services
     Required Skills: Basic Computer Skills, Embedded Systems, Store Management, ServiceNow, Customer Service

============================================================
Manual Inspection Observations (Refined Recommendations):
Comparing these recommendations to the previous ones, the inclusion of n-grams in TF-IDF may have captured more nuanced relationships between terms.
Look for recommendations that might be more specific or better aligned with combinations of skills or industries mentioned in the student profile.
Note if the rankings of internships have changed significantly or if different internships appear in the top N.